spring:
  application:
    name: msvc-cursos
  datasource:
    url: jdbc:postgresql://localhost:5432/msvc-cursos
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    generate-ddl: true
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true

logging:
  level:
    org:
      hibernate:
        SQL: debug

server:
  port: 8002
